CREATE TYPE "role_type" AS ENUM (
  'USER',
  'ADMIN'
);

CREATE TYPE "request_status" AS ENUM (
  'PENDING',
  'APPROVED',
  'REJECTED',
  'CANCELED'
);

CREATE TYPE "flight_status" AS ENUM (
  'SCHEDULED',
  'BOARDING',
  'COMPLETED',
  'CANCELLED'
);

CREATE TYPE "transaction_type" AS ENUM (
  'DEPOSIT',
  'PURCHASE',
  'REFUND'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "created_at" timestamp DEFAULT (now()),
  "is_active" boolean DEFAULT true,
  "cached_total_spend" decimal(12,2) DEFAULT 0,
  "loyalty_tier" integer NOT NULL DEFAULT 0,
  "has_corporate_contract" boolean NOT NULL DEFAULT false,
  "no_show_count" integer NOT NULL DEFAULT 0,
  "ancillary_spend" decimal(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE "user_roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "role" role_type NOT NULL,
  "assigned_at" timestamp DEFAULT (now())
);

CREATE TABLE "cities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "country" varchar NOT NULL,
  "timezone" varchar
);

CREATE TABLE "airports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" integer NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "flights" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "origin_airport_id" integer NOT NULL,
  "destination_airport_id" integer NOT NULL,
  "departure_time" timestamp NOT NULL,
  "arrival_time" timestamp NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "total_seats" integer NOT NULL,
  "status" flight_status DEFAULT 'SCHEDULED',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "booking_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "flight_id" integer NOT NULL,
  "calculated_priority" decimal(12,2),
  "status" request_status DEFAULT 'PENDING',
  "created_at" timestamp DEFAULT (now()),
  "processed_at" timestamp
);

CREATE TABLE "tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_request_id" integer UNIQUE NOT NULL,
  "ticket_number" varchar UNIQUE NOT NULL,
  "is_active" boolean DEFAULT true,
  "issued_at" timestamp DEFAULT (now())
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "booking_request_id" integer,
  "amount" decimal(12,2) NOT NULL,
  "type" transaction_type NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "booking_request_id" integer,
  "message" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "sent_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" integer NOT NULL,
  "action" varchar NOT NULL,
  "entity_id" integer,
  "details" text,
  "created_at" timestamp DEFAULT (now())
);


ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;


ALTER TABLE "airports" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id");

ALTER TABLE "flights" ADD FOREIGN KEY ("origin_airport_id") REFERENCES "airports" ("id");

ALTER TABLE "flights" ADD FOREIGN KEY ("destination_airport_id") REFERENCES "airports" ("id");

ALTER TABLE "booking_requests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "booking_requests" ADD FOREIGN KEY ("flight_id") REFERENCES "flights" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("booking_request_id") REFERENCES "booking_requests" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("booking_request_id") REFERENCES "booking_requests" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("booking_request_id") REFERENCES "booking_requests" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("id");

ALTER TABLE flights
    ADD CONSTRAINT check_flight_dates CHECK (arrival_time > departure_time), 
    ADD CONSTRAINT check_price_positive CHECK (price >= 0), 
    ADD CONSTRAINT check_seats_positive CHECK (total_seats > 0);

ALTER TABLE flights ADD COLUMN available_seats INT;
UPDATE flights SET available_seats = total_seats;
ALTER TABLE flights ALTER COLUMN available_seats SET NOT NULL;

ALTER TABLE flights
    ADD CONSTRAINT check_availability CHECK (available_seats >= 0 AND available_seats <= total_seats);

ALTER TABLE transactions
    ADD CONSTRAINT check_transaction_amount CHECK (amount != 0);




CREATE OR REPLACE FUNCTION update_user_total_spend()
RETURNS TRIGGER AS $$
BEGIN
    
    UPDATE users
    SET cached_total_spend = (
        SELECT COALESCE(SUM(amount), 0)
        FROM transactions
        WHERE user_id = NEW.user_id AND type = 'PURCHASE'
    )
    WHERE id = NEW.user_id;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_spend
AFTER INSERT ON transactions
FOR EACH ROW
EXECUTE FUNCTION update_user_total_spend();



CREATE OR REPLACE FUNCTION check_ticket_limit()
RETURNS TRIGGER AS $$
DECLARE
    active_tickets_count INT;
BEGIN
    
    SELECT COUNT(*) INTO active_tickets_count
    FROM tickets t
    JOIN booking_requests br ON t.booking_request_id = br.id
    WHERE br.user_id = NEW.user_id 
      AND t.is_active = true
      AND br.flight_id = NEW.flight_id;

    IF active_tickets_count >= 6 THEN
        RAISE EXCEPTION 'Limit exceeded: You cannot buy more than 6 tickets for this flight';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_ticket_limit
BEFORE INSERT ON booking_requests
FOR EACH ROW
EXECUTE FUNCTION check_ticket_limit();





CREATE OR REPLACE FUNCTION decrease_flight_inventory()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE flights
    SET available_seats = available_seats - 1
    WHERE id = (SELECT flight_id FROM booking_requests WHERE id = NEW.booking_request_id);
    
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_decrease_inventory
AFTER INSERT ON tickets
FOR EACH ROW
EXECUTE FUNCTION decrease_flight_inventory();


CREATE OR REPLACE FUNCTION increase_flight_inventory()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_active = false AND OLD.is_active = true THEN
        UPDATE flights
        SET available_seats = available_seats + 1
        WHERE id = (SELECT flight_id FROM booking_requests WHERE id = NEW.booking_request_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_increase_inventory
AFTER UPDATE ON tickets
FOR EACH ROW
EXECUTE FUNCTION increase_flight_inventory();

CREATE OR REPLACE PROCEDURE process_flight_queue(p_flight_id INT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available_seats INT;
    v_price DECIMAL(10, 2);
    v_req RECORD;
    v_ticket_num TEXT;
    v_balance DECIMAL(12, 2);
BEGIN
    SELECT available_seats, price INTO v_available_seats, v_price
    FROM flights WHERE id = p_flight_id FOR UPDATE;

    IF v_available_seats IS NULL THEN
        RAISE NOTICE 'Flight not found or locked';
        RETURN;
    END IF;

    FOR v_req IN (
        SELECT id, user_id
        FROM booking_requests
        WHERE flight_id = p_flight_id AND status = 'PENDING'
        ORDER BY calculated_priority DESC, created_at ASC
    ) LOOP

	SELECT COALESCE(SUM(
			CASE
				WHEN type IN ('DEPOSIT','REFUND') THEN amount
				WHEN type = 'PURCHASE' THEN -amount
				ELSE 0
			END
		), 0) INTO v_balance
		FROM transactions
		WHERE user_id = v_req.user_id;

        IF v_available_seats > 0 THEN
	IF v_balance >= v_price THEN
            v_ticket_num := 'TKT-' || p_flight_id || '-' || v_req.id || '-' || extract(epoch from now())::int;

            INSERT INTO tickets (booking_request_id, ticket_number)
            VALUES (v_req.id, v_ticket_num);

	    INSERT INTO transactions (user_id, booking_request_id, amount, type)
	    VALUES (v_req.user_id, v_req.id, v_price, 'PURCHASE');

            UPDATE booking_requests
            SET status = 'APPROVED', processed_at = now()
            WHERE id = v_req.id;
            
            INSERT INTO notifications (user_id, booking_request_id, message)
            VALUES (v_req.user_id, v_req.id, 'Поздравляем! Ваша заявка одобрена, билет выписан. Списано: ' || v_price);

            v_available_seats := v_available_seats - 1;
	ELSE
		UPDATE booking_requests
		SET status = 'REJECTED', processed_at = now()
		WHERE id = v_req.id;

		INSERT INTO notifications (user_id, booking_request_id, message)
		VALUES (v_req.user_id, v_req.id, 'Недостаточно средств. Ваш баланс: ' || v_balance || ', цена: ' || v_price);
	END IF;

        ELSE
            UPDATE booking_requests
            SET status = 'REJECTED', processed_at = now()
            WHERE id = v_req.id;

            INSERT INTO notifications (user_id, booking_request_id, message)
            VALUES (v_req.user_id, v_req.id, 'К сожалению, билеты закончились. В следующий раз попробуйте повысить свой приоритет.');
        END IF;

    END LOOP;
    
    IF v_available_seats = 0 THEN
        UPDATE flights SET status = 'BOARDING' WHERE id = p_flight_id;
    END IF;
    
END;
$$;

CREATE OR REPLACE PROCEDURE cancel_flight_by_admin(
    p_admin_id INT,
    p_flight_id INT,
    p_reason TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_flight_status flight_status;
    v_ticket RECORD;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM user_roles WHERE user_id = p_admin_id AND role = 'ADMIN') THEN
        RAISE EXCEPTION 'Access denied: User is not an Admin';
    END IF;

    SELECT status INTO v_flight_status FROM flights WHERE id = p_flight_id;

    IF v_flight_status = 'CANCELLED' OR v_flight_status = 'COMPLETED' THEN
        RAISE EXCEPTION 'Flight is already finished or cancelled';
    END IF;

    UPDATE flights
    SET status = 'CANCELLED'
    WHERE id = p_flight_id;

    FOR v_ticket IN (
        SELECT t.id AS ticket_id, br.user_id, br.id AS req_id, f.price
        FROM tickets t
        JOIN booking_requests br ON t.booking_request_id = br.id
        JOIN flights f ON br.flight_id = f.id
        WHERE br.flight_id = p_flight_id AND t.is_active = true
    ) LOOP
        UPDATE tickets SET is_active = false WHERE id = v_ticket.ticket_id;

        INSERT INTO transactions (user_id, booking_request_id, amount, type)
        VALUES (v_ticket.user_id, v_ticket.req_id, v_ticket.price, 'REFUND');
        
        INSERT INTO notifications (user_id, booking_request_id, message)
        VALUES (v_ticket.user_id, v_ticket.req_id, 'Рейс отменен администратором. Средства возвращены. Причина: ' || p_reason);
    END LOOP;

    INSERT INTO audit_logs (admin_user_id, action, entity_id, details)
    VALUES (p_admin_id, 'CANCEL_FLIGHT', p_flight_id, 'Reason: ' || p_reason);

END;
$$;

CREATE OR REPLACE FUNCTION search_flights(
    p_origin_city TEXT,
    p_dest_city TEXT,
    p_date DATE
)
RETURNS TABLE (
    flight_id INT,
    flight_code TEXT,
    origin_city TEXT,
    origin_airport TEXT,
    dest_city TEXT,
    dest_airport TEXT,
    departure_time TIMESTAMP,
    price NUMERIC,
    available_seats INT,
    status flight_status
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f.id,
        ('FL-' || f.id)::text AS flight_code,
        c_org.name::text AS origin_city,
        a_org.name::text AS origin_airport,
        c_dst.name::text AS dest_city,
        a_dst.name::text AS dest_airport,
        f.departure_time,
        f.price,
        f.available_seats,
        f.status
    FROM flights f
    JOIN airports a_org ON f.origin_airport_id = a_org.id
    JOIN cities c_org ON a_org.city_id = c_org.id
    JOIN airports a_dst ON f.destination_airport_id = a_dst.id
    JOIN cities c_dst ON a_dst.city_id = c_dst.id
    WHERE 
        c_org.name ILIKE p_origin_city
        AND c_dst.name ILIKE p_dest_city
        AND f.departure_time::date = p_date
        AND f.status = 'SCHEDULED';
END;
$$;


CREATE OR REPLACE FUNCTION submit_booking_request(
    p_user_id INT,
    p_flight_id INT
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_req_id INT;
    v_priority DECIMAL(12,4);

    v_loyalty_tier           INT;
    v_has_corporate          BOOLEAN;
    v_no_show_count          INT;
    v_ancillary_spend        DECIMAL(12,2);

    v_purchase_count         INT;
    v_avg_order_value        DECIMAL(12,2);
    v_cancel_count           INT;
    v_total_requests         INT;
    v_days_since_last        DECIMAL(12,4);
    v_balance                DECIMAL(12,2);

    v_purchase_frequency_score   DECIMAL(8,6);
    v_average_order_value_score  DECIMAL(8,6);
    v_booking_class_score        DECIMAL(8,6);
    v_corporate_contract_score   DECIMAL(8,6);
    v_loyalty_status_score       DECIMAL(8,6);
    v_cancel_ratio               DECIMAL(8,6);
    v_no_show_ratio              DECIMAL(8,6);
    v_days_since_score           DECIMAL(8,6);
    v_bonus_balance_score        DECIMAL(8,6);
    v_ancillary_services_score   DECIMAL(8,6);
BEGIN
    SELECT loyalty_tier, has_corporate_contract, no_show_count, ancillary_spend
    INTO   v_loyalty_tier, v_has_corporate, v_no_show_count, v_ancillary_spend
    FROM   users WHERE id = p_user_id;

    SELECT COUNT(*) INTO v_purchase_count FROM transactions
    WHERE  user_id = p_user_id AND type = 'PURCHASE'
      AND  created_at >= NOW() - INTERVAL '12 months';
    v_purchase_frequency_score := LEAST(1.0, v_purchase_count::DECIMAL / 20.0);

    SELECT COALESCE(AVG(amount), 0) INTO v_avg_order_value FROM transactions
    WHERE  user_id = p_user_id AND type = 'PURCHASE';
    v_average_order_value_score := LEAST(1.0, v_avg_order_value / 50000.0);

    IF    v_avg_order_value > 30000 THEN v_booking_class_score := 1.0;
    ELSIF v_avg_order_value > 10000 THEN v_booking_class_score := 0.6;
    ELSE                                  v_booking_class_score := 0.2;
    END IF;

    v_corporate_contract_score := CASE WHEN v_has_corporate THEN 1.0 ELSE 0.0 END;
    v_loyalty_status_score := LEAST(1.0, COALESCE(v_loyalty_tier, 0)::DECIMAL / 3.0);

    SELECT COUNT(*) INTO v_cancel_count FROM booking_requests
    WHERE  user_id = p_user_id AND status = 'CANCELED';
    SELECT COUNT(*) INTO v_total_requests FROM booking_requests
    WHERE  user_id = p_user_id;
    v_cancel_ratio := CASE WHEN v_total_requests > 0
                           THEN v_cancel_count::DECIMAL / v_total_requests ELSE 0.0 END;

    v_no_show_ratio := CASE WHEN v_total_requests > 0
                            THEN COALESCE(v_no_show_count, 0)::DECIMAL / v_total_requests
                            ELSE 0.0 END;

    SELECT COALESCE(EXTRACT(EPOCH FROM (NOW() - MAX(created_at))) / 86400.0, 365)
    INTO   v_days_since_last FROM transactions
    WHERE  user_id = p_user_id AND type = 'PURCHASE';
    v_days_since_score := LEAST(1.0, v_days_since_last / 365.0);

    SELECT COALESCE(SUM(CASE WHEN type IN ('DEPOSIT','REFUND') THEN amount
                             WHEN type = 'PURCHASE' THEN -amount ELSE 0 END), 0)
    INTO   v_balance FROM transactions WHERE user_id = p_user_id;
    v_bonus_balance_score := LEAST(1.0, GREATEST(0.0, v_balance / 100000.0));

    v_ancillary_services_score := LEAST(1.0, COALESCE(v_ancillary_spend, 0) / 5000.0);

    v_priority :=
          29.22 * v_purchase_frequency_score
        + 14.15 * v_average_order_value_score
        + 11.46 * v_booking_class_score
        + 11.43 * v_corporate_contract_score
        + 11.00 * v_loyalty_status_score
        - 10.50 * v_cancel_ratio
        -  5.53 * v_no_show_ratio
        -  2.93 * v_days_since_score
        +  2.03 * v_bonus_balance_score
        +  1.76 * v_ancillary_services_score;

    IF v_priority < 0 THEN v_priority := 0; END IF;

    INSERT INTO booking_requests (user_id, flight_id, calculated_priority, status)
    VALUES (p_user_id, p_flight_id, v_priority, 'PENDING')
    RETURNING id INTO v_req_id;

    RETURN v_req_id;
END;
$$;

CREATE INDEX idx_booking_queue 
ON booking_requests (flight_id, status, calculated_priority DESC);

CREATE INDEX idx_flights_search 
ON flights (origin_airport_id, destination_airport_id, departure_time);

CREATE INDEX idx_transactions_user 
ON transactions (user_id);
